name:                sofetch-otel
version:             0.1.0.0
github:              "iand675/sofetch"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

description:         OpenTelemetry instrumentation for sofetch

dependencies:
- base >= 4.7 && < 5
- sofetch
- hs-opentelemetry-api

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  sofetch-otel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sofetch-otel
    - sofetch
    - hspec
    - unordered-containers
